/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AppRouteImport } from './routes/app'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DesignMascotRouteImport } from './routes/design-mascot'
import { Route as DesignStatusBadgeRouteImport } from './routes/design-status-badge'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppDeliveriesRouteImport } from './routes/app.deliveries'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppPackRouteImport } from './routes/app.pack'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as DesignInboxSimulatorRouteImport } from './routes/design.inbox-simulator'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppCustomersIndexRouteImport } from './routes/app.customers.index'
import { Route as AppCustomersIdRouteImport } from './routes/app.customers.$id'
import { Route as AppDeliveriesIdRouteImport } from './routes/app.deliveries.$id'
import { Route as AppInboxIdRouteImport } from './routes/app.inbox.$id'
import { Route as AppInventoryVariantIdRouteImport } from './routes/app.inventory.$variantId'
import { Route as AppOrdersIdRouteImport } from './routes/app.orders.$id'
import { Route as AppParcelsCodeRouteImport } from './routes/app.parcels.$code'
import { Route as AppPaymentsIdRouteImport } from './routes/app.payments.$id'
import { Route as AppProductsIdRouteImport } from './routes/app.products.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignMascotRoute = DesignMascotRouteImport.update({
  id: '/design-mascot',
  path: '/design-mascot',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignStatusBadgeRoute = DesignStatusBadgeRouteImport.update({
  id: '/design-status-badge',
  path: '/design-status-badge',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesRoute = AppDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppPackRoute = AppPackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const DesignInboxSimulatorRoute = DesignInboxSimulatorRouteImport.update({
  id: '/inbox-simulator',
  path: '/inbox-simulator',
  getParentRoute: () => DesignRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesIdRoute = AppDeliveriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDeliveriesRoute,
} as any)
const AppInboxIdRoute = AppInboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppInventoryVariantIdRoute = AppInventoryVariantIdRouteImport.update({
  id: '/$variantId',
  path: '/$variantId',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppParcelsCodeRoute = AppParcelsCodeRouteImport.update({
  id: '/parcels/$code',
  path: '/parcels/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIdRoute = AppPaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/app': typeof AppRouteWithChildren
  '/design': typeof DesignRouteWithChildren
  '/design-mascot': typeof DesignMascotRoute
  '/design-status-badge': typeof DesignStatusBadgeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/deliveries': typeof AppDeliveriesRouteWithChildren
  '/app/inbox': typeof AppInboxRouteWithChildren
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/pack': typeof AppPackRoute
  '/app/payments': typeof AppPaymentsRouteWithChildren
  '/app/pos': typeof AppPosRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/design/inbox-simulator': typeof DesignInboxSimulatorRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/deliveries/$id': typeof AppDeliveriesIdRoute
  '/app/inbox/$id': typeof AppInboxIdRoute
  '/app/inventory/$variantId': typeof AppInventoryVariantIdRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/parcels/$code': typeof AppParcelsCodeRoute
  '/app/payments/$id': typeof AppPaymentsIdRoute
  '/app/products/$id': typeof AppProductsIdRoute
  '/app/customers/': typeof AppCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/design': typeof DesignRouteWithChildren
  '/design-mascot': typeof DesignMascotRoute
  '/design-status-badge': typeof DesignStatusBadgeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/deliveries': typeof AppDeliveriesRouteWithChildren
  '/app/inbox': typeof AppInboxRouteWithChildren
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/pack': typeof AppPackRoute
  '/app/payments': typeof AppPaymentsRouteWithChildren
  '/app/pos': typeof AppPosRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/design/inbox-simulator': typeof DesignInboxSimulatorRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app': typeof AppIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/deliveries/$id': typeof AppDeliveriesIdRoute
  '/app/inbox/$id': typeof AppInboxIdRoute
  '/app/inventory/$variantId': typeof AppInventoryVariantIdRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/parcels/$code': typeof AppParcelsCodeRoute
  '/app/payments/$id': typeof AppPaymentsIdRoute
  '/app/products/$id': typeof AppProductsIdRoute
  '/app/customers': typeof AppCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/app': typeof AppRouteWithChildren
  '/design': typeof DesignRouteWithChildren
  '/design-mascot': typeof DesignMascotRoute
  '/design-status-badge': typeof DesignStatusBadgeRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/deliveries': typeof AppDeliveriesRouteWithChildren
  '/app/inbox': typeof AppInboxRouteWithChildren
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/pack': typeof AppPackRoute
  '/app/payments': typeof AppPaymentsRouteWithChildren
  '/app/pos': typeof AppPosRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/design/inbox-simulator': typeof DesignInboxSimulatorRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/deliveries/$id': typeof AppDeliveriesIdRoute
  '/app/inbox/$id': typeof AppInboxIdRoute
  '/app/inventory/$variantId': typeof AppInventoryVariantIdRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/parcels/$code': typeof AppParcelsCodeRoute
  '/app/payments/$id': typeof AppPaymentsIdRoute
  '/app/products/$id': typeof AppProductsIdRoute
  '/app/customers/': typeof AppCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/app'
    | '/design'
    | '/design-mascot'
    | '/design-status-badge'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/app/analytics'
    | '/app/deliveries'
    | '/app/inbox'
    | '/app/inventory'
    | '/app/orders'
    | '/app/pack'
    | '/app/payments'
    | '/app/pos'
    | '/app/products'
    | '/app/settings'
    | '/app/team'
    | '/design/inbox-simulator'
    | '/invite/$token'
    | '/app/'
    | '/app/customers/$id'
    | '/app/deliveries/$id'
    | '/app/inbox/$id'
    | '/app/inventory/$variantId'
    | '/app/orders/$id'
    | '/app/parcels/$code'
    | '/app/payments/$id'
    | '/app/products/$id'
    | '/app/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/design'
    | '/design-mascot'
    | '/design-status-badge'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/app/analytics'
    | '/app/deliveries'
    | '/app/inbox'
    | '/app/inventory'
    | '/app/orders'
    | '/app/pack'
    | '/app/payments'
    | '/app/pos'
    | '/app/products'
    | '/app/settings'
    | '/app/team'
    | '/design/inbox-simulator'
    | '/invite/$token'
    | '/app'
    | '/app/customers/$id'
    | '/app/deliveries/$id'
    | '/app/inbox/$id'
    | '/app/inventory/$variantId'
    | '/app/orders/$id'
    | '/app/parcels/$code'
    | '/app/payments/$id'
    | '/app/products/$id'
    | '/app/customers'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/app'
    | '/design'
    | '/design-mascot'
    | '/design-status-badge'
    | '/forgot-password'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/app/analytics'
    | '/app/deliveries'
    | '/app/inbox'
    | '/app/inventory'
    | '/app/orders'
    | '/app/pack'
    | '/app/payments'
    | '/app/pos'
    | '/app/products'
    | '/app/settings'
    | '/app/team'
    | '/design/inbox-simulator'
    | '/invite/$token'
    | '/app/'
    | '/app/customers/$id'
    | '/app/deliveries/$id'
    | '/app/inbox/$id'
    | '/app/inventory/$variantId'
    | '/app/orders/$id'
    | '/app/parcels/$code'
    | '/app/payments/$id'
    | '/app/products/$id'
    | '/app/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AppRoute: typeof AppRouteWithChildren
  DesignRoute: typeof DesignRouteWithChildren
  DesignMascotRoute: typeof DesignMascotRoute
  DesignStatusBadgeRoute: typeof DesignStatusBadgeRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-mascot': {
      id: '/design-mascot'
      path: '/design-mascot'
      fullPath: '/design-mascot'
      preLoaderRoute: typeof DesignMascotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-status-badge': {
      id: '/design-status-badge'
      path: '/design-status-badge'
      fullPath: '/design-status-badge'
      preLoaderRoute: typeof DesignStatusBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deliveries': {
      id: '/app/deliveries'
      path: '/deliveries'
      fullPath: '/app/deliveries'
      preLoaderRoute: typeof AppDeliveriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pack': {
      id: '/app/pack'
      path: '/pack'
      fullPath: '/app/pack'
      preLoaderRoute: typeof AppPackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/design/inbox-simulator': {
      id: '/design/inbox-simulator'
      path: '/inbox-simulator'
      fullPath: '/design/inbox-simulator'
      preLoaderRoute: typeof DesignInboxSimulatorRouteImport
      parentRoute: typeof DesignRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/$id': {
      id: '/app/customers/$id'
      path: '/customers/$id'
      fullPath: '/app/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/deliveries/$id': {
      id: '/app/deliveries/$id'
      path: '/$id'
      fullPath: '/app/deliveries/$id'
      preLoaderRoute: typeof AppDeliveriesIdRouteImport
      parentRoute: typeof AppDeliveriesRoute
    }
    '/app/inbox/$id': {
      id: '/app/inbox/$id'
      path: '/$id'
      fullPath: '/app/inbox/$id'
      preLoaderRoute: typeof AppInboxIdRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/app/inventory/$variantId': {
      id: '/app/inventory/$variantId'
      path: '/$variantId'
      fullPath: '/app/inventory/$variantId'
      preLoaderRoute: typeof AppInventoryVariantIdRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/orders/$id': {
      id: '/app/orders/$id'
      path: '/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/app/parcels/$code': {
      id: '/app/parcels/$code'
      path: '/parcels/$code'
      fullPath: '/app/parcels/$code'
      preLoaderRoute: typeof AppParcelsCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments/$id': {
      id: '/app/payments/$id'
      path: '/$id'
      fullPath: '/app/payments/$id'
      preLoaderRoute: typeof AppPaymentsIdRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/products/$id': {
      id: '/app/products/$id'
      path: '/$id'
      fullPath: '/app/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppProductsRoute
    }
  }
}

interface AppDeliveriesRouteChildren {
  AppDeliveriesIdRoute: typeof AppDeliveriesIdRoute
}

const AppDeliveriesRouteChildren: AppDeliveriesRouteChildren = {
  AppDeliveriesIdRoute: AppDeliveriesIdRoute,
}

const AppDeliveriesRouteWithChildren = AppDeliveriesRoute._addFileChildren(
  AppDeliveriesRouteChildren,
)

interface AppInboxRouteChildren {
  AppInboxIdRoute: typeof AppInboxIdRoute
}

const AppInboxRouteChildren: AppInboxRouteChildren = {
  AppInboxIdRoute: AppInboxIdRoute,
}

const AppInboxRouteWithChildren = AppInboxRoute._addFileChildren(
  AppInboxRouteChildren,
)

interface AppInventoryRouteChildren {
  AppInventoryVariantIdRoute: typeof AppInventoryVariantIdRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryVariantIdRoute: AppInventoryVariantIdRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppOrdersRouteChildren {
  AppOrdersIdRoute: typeof AppOrdersIdRoute
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersIdRoute: AppOrdersIdRoute,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppPaymentsRouteChildren {
  AppPaymentsIdRoute: typeof AppPaymentsIdRoute
}

const AppPaymentsRouteChildren: AppPaymentsRouteChildren = {
  AppPaymentsIdRoute: AppPaymentsIdRoute,
}

const AppPaymentsRouteWithChildren = AppPaymentsRoute._addFileChildren(
  AppPaymentsRouteChildren,
)

interface AppProductsRouteChildren {
  AppProductsIdRoute: typeof AppProductsIdRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsIdRoute: AppProductsIdRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDeliveriesRoute: typeof AppDeliveriesRouteWithChildren
  AppInboxRoute: typeof AppInboxRouteWithChildren
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppPackRoute: typeof AppPackRoute
  AppPaymentsRoute: typeof AppPaymentsRouteWithChildren
  AppPosRoute: typeof AppPosRoute
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppParcelsCodeRoute: typeof AppParcelsCodeRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDeliveriesRoute: AppDeliveriesRouteWithChildren,
  AppInboxRoute: AppInboxRouteWithChildren,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppPackRoute: AppPackRoute,
  AppPaymentsRoute: AppPaymentsRouteWithChildren,
  AppPosRoute: AppPosRoute,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppParcelsCodeRoute: AppParcelsCodeRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DesignRouteChildren {
  DesignInboxSimulatorRoute: typeof DesignInboxSimulatorRoute
}

const DesignRouteChildren: DesignRouteChildren = {
  DesignInboxSimulatorRoute: DesignInboxSimulatorRoute,
}

const DesignRouteWithChildren =
  DesignRoute._addFileChildren(DesignRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AppRoute: AppRouteWithChildren,
  DesignRoute: DesignRouteWithChildren,
  DesignMascotRoute: DesignMascotRoute,
  DesignStatusBadgeRoute: DesignStatusBadgeRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
