/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignRouteImport } from './routes/design'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppCustomersIdRouteImport } from './routes/app.customers.$id'
import { Route as AppDeliveriesIdRouteImport } from './routes/app.deliveries.$id'
import { Route as AppInboxIdRouteImport } from './routes/app.inbox.$id'
import { Route as AppOrdersIdRouteImport } from './routes/app.orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/app/inbox',
  path: '/app/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/app/pos',
  path: '/app/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/app/customers/$id',
  path: '/app/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDeliveriesIdRoute = AppDeliveriesIdRouteImport.update({
  id: '/app/deliveries/$id',
  path: '/app/deliveries/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInboxIdRoute = AppInboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/app/orders/$id',
  path: '/app/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/app/inbox': typeof AppInboxRouteWithChildren
  '/app/pos': typeof AppPosRoute
  '/app/': typeof AppIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/deliveries/$id': typeof AppDeliveriesIdRoute
  '/app/inbox/$id': typeof AppInboxIdRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/app/inbox': typeof AppInboxRouteWithChildren
  '/app/pos': typeof AppPosRoute
  '/app': typeof AppIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/deliveries/$id': typeof AppDeliveriesIdRoute
  '/app/inbox/$id': typeof AppInboxIdRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/app/inbox': typeof AppInboxRouteWithChildren
  '/app/pos': typeof AppPosRoute
  '/app/': typeof AppIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/deliveries/$id': typeof AppDeliveriesIdRoute
  '/app/inbox/$id': typeof AppInboxIdRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design'
    | '/app/inbox'
    | '/app/pos'
    | '/app/'
    | '/app/customers/$id'
    | '/app/deliveries/$id'
    | '/app/inbox/$id'
    | '/app/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design'
    | '/app/inbox'
    | '/app/pos'
    | '/app'
    | '/app/customers/$id'
    | '/app/deliveries/$id'
    | '/app/inbox/$id'
    | '/app/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/app/inbox'
    | '/app/pos'
    | '/app/'
    | '/app/customers/$id'
    | '/app/deliveries/$id'
    | '/app/inbox/$id'
    | '/app/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  AppInboxRoute: typeof AppInboxRouteWithChildren
  AppPosRoute: typeof AppPosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppDeliveriesIdRoute: typeof AppDeliveriesIdRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/app/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/app/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/customers/$id': {
      id: '/app/customers/$id'
      path: '/app/customers/$id'
      fullPath: '/app/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/deliveries/$id': {
      id: '/app/deliveries/$id'
      path: '/app/deliveries/$id'
      fullPath: '/app/deliveries/$id'
      preLoaderRoute: typeof AppDeliveriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inbox/$id': {
      id: '/app/inbox/$id'
      path: '/$id'
      fullPath: '/app/inbox/$id'
      preLoaderRoute: typeof AppInboxIdRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/app/orders/$id': {
      id: '/app/orders/$id'
      path: '/app/orders/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppInboxRouteChildren {
  AppInboxIdRoute: typeof AppInboxIdRoute
}

const AppInboxRouteChildren: AppInboxRouteChildren = {
  AppInboxIdRoute: AppInboxIdRoute,
}

const AppInboxRouteWithChildren = AppInboxRoute._addFileChildren(
  AppInboxRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  AppInboxRoute: AppInboxRouteWithChildren,
  AppPosRoute: AppPosRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppDeliveriesIdRoute: AppDeliveriesIdRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
