-- Migration: 048_product_images
-- Purpose: V1 primary product photo — presentation/catalog metadata only.
-- Repo-only: NOT applied to any hosted project by this change (staging rehearsal
-- is paused). Apply through the normal reviewed staging → production path.
--
-- Design
--   * ONE primary image per product: products.image_path (NULL = no image).
--     A future gallery would add a product_images table; nothing here blocks it.
--   * Images live in a PRIVATE storage bucket `product-images`. There is no
--     public URL. The server returns short-lived signed URLs to callers that
--     hold products.read.
--   * Object path = <organization_id>/<product_id>/<uuid>.<jpg|png|webp>,
--     generated by the server — a client filename never reaches a path.
--   * The CHECK below pins image_path to the row's OWN organization and product,
--     so even a service-role write cannot attach another tenant's object.
--   * Bucket enforces size (5 MiB) and MIME (JPEG/PNG/WebP) itself. SVG, HTML
--     and executable types are not in the allow-list. The server additionally
--     sniffs magic bytes before it will point a product at an object.
--   * storage.objects has RLS on by default and this migration adds NO policy
--     for anon/authenticated, so browsers can neither read nor write objects
--     directly: every upload uses a server-issued signed upload URL bound to one
--     path, every read uses a server-issued signed read URL. The service role
--     (server only) bypasses RLS as usual.
--
-- Cleanup: replace/remove sets the DB reference FIRST and deletes the old object
-- afterwards (best-effort). A failed delete leaves an unreferenced object, never
-- a broken product. Orphans are identifiable as objects whose name is not any
-- products.image_path; see docs/PRODUCT_IMAGES.md for the sweep query.

ALTER TABLE public.products
  ADD COLUMN image_path TEXT,
  ADD COLUMN image_updated_at TIMESTAMPTZ;

ALTER TABLE public.products
  ADD CONSTRAINT products_image_path_owned CHECK (
    image_path IS NULL
    OR image_path ~ (
      '^' || organization_id::text || '/' || id::text ||
      '/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp)$'
    )
  );

-- One object is never shared by two products.
CREATE UNIQUE INDEX uniq_products_image_path
  ON public.products(image_path)
  WHERE image_path IS NOT NULL;

-- The bucket only exists where Supabase Storage does. The guard keeps this
-- migration replayable on plain Postgres (local migration-replay test harnesses
-- have no `storage` schema); on every Supabase project the branch always runs.
DO $$
BEGIN
  IF to_regclass('storage.buckets') IS NOT NULL THEN
    INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    VALUES (
      'product-images',
      'product-images',
      false,
      5242880,
      ARRAY['image/jpeg', 'image/png', 'image/webp']
    )
    ON CONFLICT (id) DO UPDATE
      SET public = false,
          file_size_limit = 5242880,
          allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp'];
  ELSE
    RAISE NOTICE 'storage.buckets not found — product-images bucket NOT created';
  END IF;
END
$$;
